import os

def configure(conf):

    conf.load('calibre_drc')

def build(bld):

    bld (
        features = 'calibre_drc',
        cellname = 'inverter',
        layout_gds = bld.path.find_node('../brick_test_inverter.gds'),
        includes = [bld.root.find_node('/cad/libs/tsmc/oa/Calibre/drc/calibre.drc')],
        unselect_checks = [
            #'M9.DN.2L',
        ]
    )

def run(bld):
    bld (
        features = 'calibre_rve_drc',
        cellname = 'inverter',
        gds = bld.path.find_node('../brick_test_inverter.gds'),
    )

from waflib.Build import BuildContext
class one(BuildContext):
    cmd = 'run'
    fun = 'run'

