import os

def configure(conf):

    conf.load('calibre_pex')

def build(bld):

    pex = bld (
        name = 'xrc_inverter',
        features = 'calibre_pex',
        cellname = 'inverter',
        layout_gds = bld.path.find_node('../brick_test_inverter.gds'),
        includes = [bld.root.find_node(os.environ['BRICK_DIR']+'/source/calibre/pex.rules')],
    )

