def configure(conf):
    conf.load('brick_general')
    conf.load('modelsim')

def build(bld):
    bld.load('brick_general')

    bld (
        name = 'compile_top',
        source = bld.convert_string_paths(
            [
                'tb.sv',
                'top.sv',
            ])
            ,
        features = 'modelsim',
    )


def run(bld):
    bld (
        features = 'vsim',
        toplevel = 'worklib.tb',
    )

from waflib.Build import BuildContext
class one(BuildContext):
    cmd = 'run'
    fun = 'run'

