
def configure(conf):
    conf.load('modelsim')
    conf.env.VSIM_OPTIONS = ['-vopt','-voptargs=+acc']

def build(bld):

    bld (
        name = 'compile_top',
        source = bld.convert_string_paths(
            [
                '../../source/systemverilog/package.sv',
                '../../source/systemverilog/tb.sv',
                '../../source/systemverilog/top.sv',
                '../../source/systemverilog/inverter.sv',
                '../../source/systemverilog/inverter_array.sv',
            ])
            ,
        features = 'modelsim',
        verilog_search_paths = bld.convert_string_paths(['../../source/verilog'])
    )


def run(bld):
    bld (
        features = 'vsim',
        toplevel = 'worklib.tb',
    )

from waflib.Build import BuildContext
class one(BuildContext):
    cmd = 'run'
    fun = 'run'

