def run(bld):
    # elaboration
    bld(
        name  = 'elab',
        rule  = 'ncelab ${SIMULATION_TOPLEVEL} -logfile ${CURRENT_RUNDIR}/logfiles/ncelab.log ${NCELAB_OPTIONS} ',
        always = True
    )
    # simulation
    bld(
       rule  = 'ncsim -logfile ${CURRENT_RUNDIR}/logfiles/ncsim.log ${SIMULATION_TOPLEVEL} ${NCSIM_OPTIONS}',
       after = 'elab',
       always = True
    )
