import os

def configure(conf):
    conf.load('cadence_ius')
    conf.env.NCELAB_OPTIONS.extend(['-access','+r'])

    conf.env['CDS_LIBS'] = {
            'ieee': os.environ['IUSDIR']+'/tools/inca/files/IEEE',
            'std': os.environ['IUSDIR']+'/tools/inca/files/STD',
            }

def build(bld):
    bld ( features = 'cds_write_libs' )

    bld (
        name = 'compile_top',
        source = bld.convert_string_paths(
            [
                '../../source/systemverilog/package.sv',
                '../../source/systemverilog/tb.sv',
                '../../source/systemverilog/top.sv',
                '../../source/systemverilog/inverter.sv',
                '../../source/systemverilog/inverter_array.sv',
                '../../source/vhdl/empty.vhd',
            ]),
        features = 'cds_compile_hdl',
        verilog_search_paths = bld.convert_string_paths(['../../source/verilog'])
    )
    bld.add_group()
    bld (
        toplevel = 'worklib.tb',
        features = 'cds_elab',
        always = True
    )

def run(bld):
    bld (
        features = 'ncsim',
        toplevel = 'worklib.tb',
    )

from waflib.Build import BuildContext
class one(BuildContext):
    cmd = 'run'
    fun = 'run'

