def run(bld):
   # bld(
   #    rule = 'vopt -l ${CURRENT_RUNDIR}/logfiles/vopt.log ${VOPT_OPTIONS}',
   #    name = 'vopt',
   #    always = True,
   #)
    # simulation
    bld(
       rule  = 'vsim -l ${CURRENT_RUNDIR}/logfiles/vsim.log ${SIMULATION_TOPLEVEL} ${VSIM_OPTIONS}',
       always = True,
       after = 'vopt',
    )
